### PR TITLE
Migration to Meteor 3.0

### PR DESCRIPTION
**Pull request by jankapunkt**
- [x] updated package versions
- [x] test project with 3.0
- [x] self-tests running
- [x] CI to GitHub actions

### CODE REVIEW

**Comment by harryadel** [comment]
The changes so far are good. :+1:

**Review by harryadel — APPROVED** [review]

**Comment by ToyboxZach** [comment]
I'm not sure where to put issues for this, but I was trying this out to get my Meteor 3.0 tested and for the client unit tests it seems unable to run any of my tests

```

describe.only("My group", () => {
  console.log("Group started);

  it.only("My test", () => {
    console.log("Test started");
```

It will print out the "Group started" but never the "test started" and then it will just hang.

I am running into other problems with my integration tests, but I haven't figured out if its this package or puppeteer causing the issue.

**Comment by jankapunkt** [comment]
@ToyboxZach please create a new issue and link this PR. Please add some info for reproduction or link a minimal reproduction repo. I'll take a look at it.

**Comment by jankapunkt** [comment]
Note that it's likely an issue with it.only as we upgraded to mocha v 10.

**Comment by ToyboxZach** [comment]
It has nothing to do with only. Nothing works, even in the most basic case:

https://github.com/Meteor-Community-Packages/meteor-mocha/issues/151

**Comment by jankapunkt** [comment]
published `3.1.0-rc.0` @ToyboxZach @StorytellerCZ 

- fixed back-compat with 2.x in mocha-core
- upgraded versionsFrom towards 2.8.0 and 3.0-rc.2
- upgrade browser-tests versionsFrom

**Comment by jankapunkt** [comment]
@StorytellerCZ can you please remove this project from circleCI or do we need to contact someone else for that?

**Comment by StorytellerCZ** [comment]
Removed the hook in the settings. We no longer have any integration set for this and I think the settings file is also gone, so hopefully that check will be gone in next push.

**Comment by StorytellerCZ** [comment]
Fixed the version @jankapunkt, I think this is ready for release now.

**Comment by jankapunkt** [comment]
@StorytellerCZ yes it was working well with the previous RC packages so you can release, please also add review so I can merge

**Review by StorytellerCZ — APPROVED** [review]

**Review by nachocodoner — APPROVED** [review]
It is hard to see what was changed, since it included many formatting changes as part of this PR. Anyway, looks good.

**Comment by denihs** [comment]
Just publish version 3.0.0 for this package https://github.com/Meteor-Community-Packages/meteor-mocha/pull/155

**Comment by StorytellerCZ** [comment]
Why is there also version 3.0.3?

**Pull request merged**
